apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-thomas-vaultwarden
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    requests.storage: "20Gi"
    persistentvolumeclaims: "2"
    count/deployments.apps: "3"
    pods: "10"
