apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-action3062-homepage
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: "768Mi"
    limits.cpu: "750m"
    limits.memory: "768Mi"
    requests.storage: "5Gi"
    persistentvolumeclaims: "2"
    count/deployments.apps: "3"
    pods: "10"
