apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: tenant-action3062-homepage
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:yyJluUkPdgFR7DSmkHiuehRnmlQg3wGEZ/25u+B7lnmj/cRovV+H8Rdru54y2FBf04+24hlGLyqeGZdRgxHDxg==,iv:JKuUnIgQHh5kkZWJv3xA8wFb6Swgg3tu+IxNYgNLSJI=,tag:iasz2jmVkLxbCEGfwbMcrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v692qut43hq0k07jz6afe75txgtjjpffe0nsyw9qx55p8s5qj50scylpqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZEI3YVBZMUdRODlpWFY4
            VWl0VHZSMW9KSTdYUkNqd0piT0RvcUtKMW5jCnp4aHZiZjNyamw2TEtJT2g5dW5V
            aWFYTUx0dktROERqSzJSZmdpbVFWREUKLS0tIFhXallLZzY3WGZJelhnS3AxUmsz
            Y01CMGVZeTBDU2VmdjI4ekhub0RsWU0KD3EeE2Bk5ozRBVdlsh0zhNnXaVPAUspA
            S6rWHi4YiWcrAoqka7U48kVXXuCHMIOIR49veGX7FV1P2ewI8Ftvww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T20:26:24Z"
    mac: ENC[AES256_GCM,data:dQ9heGB0OGLMKGDQfi2B62rT7j2jO++sAfud4dbUQ3WE+bgTLmG/pa5gG4gr7T7iI2OuGLRGt1agVPCiBktbX2B6tPsbrIDSM+TFSO4bTQJANZEbsrMSwBTSvnyDTpRighNCDSFztlN59M/6w62mLcw1qyo0oCLbBq8SJokd+MY=,iv:ihJnaF/0RD+Bo3aHP0jGqJhbWTRQV/IQPWZXK2JNQlI=,tag:rGXAfHRNRPIAmx9Osrf4Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
