import YAML from 'yaml';

export interface HelmReleaseOpts {
  name: string;          // metadata.name (z. B. <kunde>-<app>)
  namespace: string;     // targetNamespace
  appChart: string;      // chart-Verzeichnis unter platform/catalog/<appChart>
  values: Record<string, unknown>;
}

export function renderHelmRelease(opts: HelmReleaseOpts): string {
  const doc = {
    apiVersion: 'helm.toolkit.fluxcd.io/v2',
    kind: 'HelmRelease',
    metadata: { name: opts.name, namespace: 'flux-system' },
    spec: {
      interval: '10m',
      releaseName: opts.appChart,
      targetNamespace: opts.namespace,
      storageNamespace: opts.namespace,
      install: { createNamespace: false },
      upgrade: { remediation: { retries: 3 } },
      chart: {
        spec: {
          chart: `./platform/catalog/${opts.appChart}`,
          sourceRef: { kind: 'GitRepository', name: 'flux-system', namespace: 'flux-system' },
        },
      },
      values: opts.values,
    },
  };
  return '# Generated by DynStore control-plane — do not edit by hand.\n' + YAML.stringify(doc);
}
