apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer-dns01.yaml
  - wildcard-cert.yaml          # vaultwarden — pro weiterer App eine Kopie ergaenzen
  - wildcard-cert-openclaw.yaml
