apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer-dns01.yaml
  - wildcard-cert.yaml          # vaultwarden — pro weiterer App eine Kopie ergaenzen
  - wildcard-cert-openclaw.yaml
  - wildcard-cert-radarr.yaml
  - wildcard-cert-seerr.yaml
  - wildcard-cert-sonarr.yaml
  - wildcard-cert-bazarr.yaml
  - wildcard-cert-notifiarr.yaml
  - wildcard-cert-homepage.yaml
  - wildcard-cert-uptime-kuma.yaml
