apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-bazarr
  namespace: cert-manager
spec:
  secretName: wildcard-bazarr-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tenant-.*-bazarr"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "tenant-.*-bazarr"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.bazarr.meinappnest.org"
  dnsNames:
    - "*.bazarr.meinappnest.org"
