apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-sonarr
  namespace: cert-manager
spec:
  secretName: wildcard-sonarr-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tenant-.*-sonarr"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "tenant-.*-sonarr"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.sonarr.meinappnest.org"
  dnsNames:
    - "*.sonarr.meinappnest.org"
