apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-jellyfin
  namespace: cert-manager
spec:
  secretName: wildcard-jellyfin-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tenant-.*-jellyfin"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "tenant-.*-jellyfin"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.jellyfin.meinappnest.org"
  dnsNames:
    - "*.jellyfin.meinappnest.org"
