apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homepage
  namespace: cert-manager
spec:
  secretName: wildcard-homepage-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tenant-.*-homepage"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "tenant-.*-homepage"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.homepage.meinappnest.org"
  dnsNames:
    - "*.homepage.meinappnest.org"
