apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: seerr
  namespace: flux-system
spec:
  image: ghcr.io/action3062/seerr
  interval: 5m
  secretRef:
    name: ghcr-pull        # privates GHCR-Package
