apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    app: uptime-kuma
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
      annotations:
        meinappnest.io/restart-token: "{{ .Values.restartToken | default "" }}"
    spec:
      containers:
        - name: uptime-kuma
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources: {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "uptime-kuma.fullname" . }}-data-v{{ .Values.dataVersion | default 1 }}
