apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openclaw.fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoint }}
    {{- if .Values.gate.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "openclaw.fullname" . }}-gate@kubernetescrd
    {{- end }}
    {{- if .Values.ingress.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ include "openclaw.host" . }}
      http:
        paths:
          {{- if .Values.webcli.enabled }}
          - path: /cli
            pathType: Prefix
            backend:
              service:
                name: {{ include "openclaw.fullname" . }}-cli
                port:
                  number: 80
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openclaw.fullname" . }}
                port:
                  number: 80
  {{- if .Values.ingress.certIssuer }}
  tls:
    - hosts: [ {{ include "openclaw.host" . | quote }} ]
      secretName: {{ include "openclaw.fullname" . }}-tls
  {{- else if not .Values.ingress.useDefaultWildcardCert }}
  tls:
    - hosts: [ {{ include "openclaw.host" . | quote }} ]
      secretName: wildcard-{{ .Values.appName }}-tls
  {{- end }}
