apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}
spec:
  selector:
    app: openclaw
  ports:
    - name: gateway
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    {{- if .Values.webcli.enabled }}
    - name: cli
      port: {{ .Values.webcli.port }}
      targetPort: {{ .Values.webcli.port }}
    {{- end }}
