apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: tenant-.*
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: tenant-.*
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:9+6kDzNm/5gPRjDTu83ngQoIKSRvMFaYvA+gpzUxqcqrVsvBpYuchmNCOwIhzNeXeZG+X3IiLkXppdO9ZpkltyO/1ADxbVpFonGARPwUWTSluc+dRR2gKzqACVFbXWATrmAipRpyukEdxK3gOlGh14HQSlpbtZkLyATBPCFBsOPa4GEV/sIkjkzcobLi81ICD+Zzpu+/ukEKu0xr/+SxvV4wI4+vRFf0gtoAWlfVEI7yHv6dwHE0E2Xb,iv:NZCWLYrISjjjsLjugTd4fBYU1f6eiStfGHENn6uyhZs=,tag:rtRUVb36TdZLKt6bOzpJgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v692qut43hq0k07jz6afe75txgtjjpffe0nsyw9qx55p8s5qj50scylpqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bDU4TElMd0pQU01yWDlk
            UU9IMnd4SUJ1YnZUMkZ1RXJHWHJ5L2ZWUmswCmNGZTdzc1RvVFpvTk1uTXBmQjlr
            aWlrWkxpNG95QWc4U3lGL25CRGxWQjQKLS0tIDcrMldpTmMvOUIxSWZVUlU2TkRn
            VFBRMHVsQ1AwSXpld2phM0J0RWN6NkkKxQ//9u5TiFJDXRKhQJT/+ksuoNHQjr/M
            TFygHAwi4gvQCIGalHox+Zpfud4C+/PqY6r7HDLSD3V9v/fkmB9WNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T23:18:40Z"
    mac: ENC[AES256_GCM,data:f/FIlQYUM6TDZhxEhY+RdJOIM05l3R5arZLT37V0vL6G6EH8NR9zVi1ubCCTo1BUQ/6D96hkSmgsXv+BHZhOv2znLXVzWPHUvbdqNb/qrbC3dpyqrc35S9CpaQooICmnFNuv/ED7/fA4rw3dMcE6Zr3wbqBYhu13xMUYi8l3/L8=,iv:3lb3f7eaMEDwpM8eZefozet5p0JPR4KyVs+J0uC/YA4=,tag:5Q4EhTwmq0jJ3psIjdG49A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
