apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: tenant-.*-vaultwarden
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: tenant-.*-vaultwarden
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:oVLVO/17qTYiRrYUq3cKGXunXCnv3nNd+mb1keL80Aa0PUiLObXLXaPcpslcS/W0TbXJ2KYecIl+2goHi990Jdjsois5n+3osA+PbVFIW/HbQw9iyemh1VuFTcBTLcqgMNvWR3iVGlMmMv3PM7WC+vl+leJOhOtFRlIoJnfl4vhpDG2umDtcfzu2cNP7K5/e94DCn9Ja/bgs6/6U3G57xFND+UJ0BvQXGIsFtUh5dD3XebeG1LehTXCP,iv:gtKAfNB0QjghMokN8Fwl98P2P59SlvFLbg+DnNyIobY=,tag:aTerRd/G3e/KzPunjsmg2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v692qut43hq0k07jz6afe75txgtjjpffe0nsyw9qx55p8s5qj50scylpqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcWNyMHVacGJiSmZGWlU5
            TkpBUjlrdkd1ODY2RklsZks2YWtqUnRFb0JZCldFQ0M5R2d3V2YyRExkVlNVWGRh
            TzBCMFBiTnM4SE9oSVN2SG5oVEVvTXMKLS0tIHRCRGtTOXpySjF0TlRxb3Z0bld0
            WnpmUHE3clVVREViYzE5M1YrUGdseFkK030G8vVfYMkoRox206YEsxqeLWw6Z/yT
            mo04p8JWDLYzR7RXakcaRCfZj5AC7ruCktkXvIGElZ1A6d5TjduIHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T22:02:06Z"
    mac: ENC[AES256_GCM,data:IP+g08RPV9PPgRylqNIp5m34IgzYYyACx2ggRJiz0MlV6HnB34UQlYM109gQSgcdxvs18cSiqLXMw/4N6z+WOeOM0dOTVQKGwMnDUKrXdPGNa60Q3+/DLgx0+V+9vK9A9d6GzyXdhDnEk83rLiJT2fPg0J+2OJLjFB9aAjJUAos=,iv:SFgYq/h6TPyZAgAHzgG0aC2wIOuhK2bRoQtod3UrxZo=,tag:7E5zNcGrkwqXuqTtXITeZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
