apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homepage.fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoint }}
    {{- if .Values.ingress.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ include "homepage.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homepage.fullname" . }}
                port:
                  number: 80
  {{- if .Values.ingress.certIssuer }}
  tls:
    - hosts: [ {{ include "homepage.host" . | quote }} ]
      secretName: {{ include "homepage.fullname" . }}-tls
  {{- else if not .Values.ingress.useDefaultWildcardCert }}
  tls:
    - hosts: [ {{ include "homepage.host" . | quote }} ]
      secretName: wildcard-{{ .Values.appName }}-tls
  {{- end }}
