apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homepage.fullname" . }}-data-v{{ .Values.dataVersion | default 1 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
