apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-action3062-seerr
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "500m"
    limits.memory: "512Mi"
    requests.storage: "5Gi"
    persistentvolumeclaims: "2"
    count/deployments.apps: "3"
    pods: "10"
