apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: storefront
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: storefront
  filterTags:
    pattern: '^[0-9]{14}$'   # CI Timestamp-Tag YYYYMMDDHHmmss
  policy:
    numerical:
      order: asc             # höchster Timestamp = neuestes Image
