apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-action3062-openclaw
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "1500m"
    limits.memory: "3072Mi"
    requests.storage: "10Gi"
    persistentvolumeclaims: "2"
    count/deployments.apps: "3"
    pods: "10"
