apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-action3062-openclaw
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: "256Mi"
    limits.cpu: "1"
    limits.memory: "2048Mi"
    requests.storage: "10Gi"
    persistentvolumeclaims: "2"
    count/deployments.apps: "3"
    pods: "10"
