apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: tenant-action3062-openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:n4kmfBTAuXGPDVyHPRXatLH1VexHbQploISuDHX4cR5QU9VK05XbudgBWWLj3A3zDgOYWVn9172smBwDfsByfQ==,iv:tRmWbMziq/ytSKUGxZMm/f+tT0kwgNrJojbAryabSFg=,tag:WwZOnwWcu6HKIq0yI36i3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v692qut43hq0k07jz6afe75txgtjjpffe0nsyw9qx55p8s5qj50scylpqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZFptaEN1b2RXVS8zUnRp
            Z3NIaWNvNTR5RWhJdlVyekpab0VDZ1l1VGdvCkw4dkQ2TGdUM0N3a0ZScVlEOThi
            OU5ZSWRSN3Z4dmg3VlNGbklBRUZiN2MKLS0tIEJkMVllUXlxVVgvRVEza3B0bXE1
            Sjk0enQxM3F3dkNnYlZwZWNOL0JnVDAKVVH50klgivQfcRGMeMe9L8UDX7+UrvWB
            ycwyPohESmO+pPPHM8FIGpHyg/TipdqK6xCV7dnRjbTrn3Vo9R9EmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T13:04:00Z"
    mac: ENC[AES256_GCM,data:5NmcbHGv05glZrmtSNm55kAijTd5RNANjYm2Y412NQgCKeMeMMFeGbOzB8owmP9KnQFyXzRgRV/H8Gl7XHw9vrq0SGT83iaNelzYqD+LL3juSjKHm/LffZOKNQamgGXTVkkoGWOmMX8Rdh7PlYPwxb+8wSgUwJrYQmWSwaWycRw=,iv:vlyiUTlDMkfKlZf9K7ByImjc639SieET4Qvw8O2KCi8=,tag:eZmBDqo3yfxtoedkB9pnmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
