apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: tenant-action3062-openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_AUTH_USER: ENC[AES256_GCM,data:A5x3tXONYvfISw==,iv:y1qX2+ASRS/D17wVan9ABTVeuRc9gcdBfe7XJYIc/e0=,tag:nn6yTapVJSPTSeqML8sMuQ==,type:str]
    OPENCLAW_GATEWAY_AUTH_PASSWORD: ENC[AES256_GCM,data:VbdthV84PKkqF8yHh9m8zvzewqJhU3yizjvnXylOcuUzNZ84+Xztp72qQLkgZiWJh3qKFsjbhA5uXc2dJeI/vA==,iv:YKazy5MP36wOuq0V1sy41JscvomCoyIQL4DrUqnpwOc=,tag:LRGDFyt9kelUSvQ8UhjCTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v692qut43hq0k07jz6afe75txgtjjpffe0nsyw9qx55p8s5qj50scylpqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlVUNUt1RFRHT0NOZThv
            YjNYSGRoajN0a2ExWFhPNC9oS0V0SS9rYmhFCmVVODI5ZGdpZUlZamhMb3UwWWRB
            VzQrMFRFSkhUWEtWbnZnZzRoOTc2dGsKLS0tIHgxWlQvWStTdjVVdW0zd2haNUhX
            cmdXQjduWnNubllreGNPeVcxZjFra2cKuYWnLQlrKxUqhqtaR8DsZPbOT7vlAQfc
            6VyTuJbg2sRzvew+Te5sOcYFriOZ0MlO2gW0UdGrEtDPodpjuXjrYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T00:37:29Z"
    mac: ENC[AES256_GCM,data:JzjgiywVInB+RwvTGSlBTpnZ9KOxx/wrTAhgmFQE9qyOZHs/I3dt3wUe/cmEVVUqVRukgI5JVcKegwoTN/AjgvuI6Iyb31sygOtBtQzRDrgy0waB36QmeexjkFdpuR/etydku2wEgwzVthQzj8A6Pl8WD9kZ2JoTrtGObhzPha4=,iv:dGHh2mNr+517x+OaA22xYIRVBz2b7lThVh/4WNIwryE=,tag:HqqTOJZpQuyLlgH5Gk0STg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
