apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: tenant-action3062-openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:gmPKWJfAMuRTWANA1Q0jmryRc++PHmx5HVXdDs3lYJE0+mPEKgdLLPUKEqFfKeh8SD2FqZseS6FIHjsPUqL4Yw==,iv:mFjI9kB1igIjnJGWqhF1rtAr5kQC5fbkhse/+VJFfFU=,tag:8ejFI1cu/1MtzTG5NzM1Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v692qut43hq0k07jz6afe75txgtjjpffe0nsyw9qx55p8s5qj50scylpqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcTFnK3FMbzdOeHhQTmww
            dUpXVlprbkp5UTNZekpTcTZzVk9Vb3d5V3lNCjc1NXg1MS8vS0dFRzBpQWtiSWRq
            QTVIdm5IRzBUYmJuc0V1bU5JNjNmTDAKLS0tIG4vWlorNGJFOWN2NytnMXFoc1NU
            RUhRaXdUMTlsVHRuelo3Tit2Tk5lV28KwFREOawUvxmHfBEZlPiVOAb7C0wm5pkq
            seomVD9IOEOJp1LF700SnyCxP/FXUKO4CYH0IYTtQk6Y0o5dni3tfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T20:04:21Z"
    mac: ENC[AES256_GCM,data:arQOR7ZWrZ+0NiyLTBh2NldRt9l1dYjS5Ru8PWJsUVzCOaoYLiVF9Q6FshHWwdvhiEK5urryZXZgmULsi9rO+P42Ss/xgQorxxFREdHjW3km8Ggl+OPT7sLEiT3OX55hGy/nB/m3QdaLNlTMXlOBvPUocvTr1fV3oD41sejt61I=,iv:mwjUN9TRaafaEI5/t5A8BkuR0P3r0MH6R/7QQTgn+pQ=,tag:u6KEilILpQ8Ow9Bb5BRWVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
